export component HorizontalSplitter {
    // properties
    in-out property <length> value;
    in property <length> min-value: 0px;
    in property <float> multiple: 1.0;
    in property <brush> background;
    width: 5px;

    // components
    Rectangle {
        height: 100%;
        width: parent.width;
        background: parent.background;
        TouchArea {
            mouse-cursor: col-resize;
            property <bool> is-down: false;
            pointer-event(event) => {
                if (event.kind == PointerEventKind.down) {
                    is-down = true;
                }
                if (event.kind == PointerEventKind.up) {
                    is-down = false;
                }
            }
            changed mouse-x => {
                if (is-down) {
                    root.value = max(root.min-value, root.value + self.mouse-x * root.multiple);
                }
            }
        }
    }
}
