import {
    Button,
    ComboBox,
    HorizontalBox,
    Slider,
    TextEdit,
    VerticalBox,
} from "std-widgets.slint";

export struct VideoConfigInfo {
    video-option-descriptions: [string],
}
export struct VideoSettings { video-option-index: int, prescale: int, extra-mame-arguments: string }

export component VideoConfigComponent {
    // properties
    in property <bool> enabled: true;
    in property <VideoConfigInfo> config-info;
    in-out property <VideoSettings> settings: { prescale: 1 };
    property <length> label-width: 140px;

    // changed handlers
    changed settings => {
        prescale-slider.value = settings.prescale;
    }

    // controls
    VerticalBox {
        HorizontalBox {
            vertical-stretch: 0;
            Text {
                width: label-width;
                vertical-alignment: center;
                text: "Video:";
            }

            ComboBox {
                model: root.config-info.video-option-descriptions;
                current-index <=> root.settings.video-option-index;
                enabled: root.enabled;
            }
        }

        HorizontalBox {
            vertical-stretch: 0;
            Text {
                width: label-width;
                vertical-alignment: center;
                text: "Prescale:";
            }

            prescale-slider := Slider {
                minimum: 1;
                maximum: 20;
                step: 1;
                value: root.settings.prescale;
                enabled: root.enabled;
                changed(value) => {
                    root.settings.prescale = value;
                }
            }

            Text {
                vertical-alignment: center;
                text: root.settings.prescale;
            }
        }

        HorizontalBox {
            vertical-stretch: 1;
            Text {
                width: label-width;
                text: "Extra MAME Arguments:";
            }

            TextEdit {
                min-width: 140px;
                min-height: 60px;
                preferred-height: 100%;
                font-family: "Courier New";
                enabled: root.enabled;
                text <=> root.settings.extra-mame-arguments;
            }
        }
    }
}
