import {
    AboutSlint,
    Button,
    VerticalBox,
    HorizontalBox,
    StandardButton,
} from "std-widgets.slint";
import { Icons } from "../icons.slint";

export component AboutDialog inherits Window {
    title: "About BletchMAME";
    icon: Icons.bletchmame;
    in property <string> version;

    callback link-clicked(link: string);

    property <image> logo-image: @image_url("../bletchmame_wordmark.svg");

    HorizontalBox {
        Image {
            width: 192px;
            height: 192px;
            source: Icons.bletchmame;
        }

        VerticalBox {
            alignment: stretch;
            Image {
                width: 500px;
                height: self.width / root.logo-image.width * root.logo-image.height;
                source: root.logo-image;
                vertical-stretch: 0;
            }

            HorizontalBox {
                StyledText {
                    vertical-alignment: center;
                    text: @markdown("[www.bletchmame.org](https://www.bletchmame.org)");
                    default-font-size: 20px;
                    link-clicked(link) => {
                        root.link-clicked(link);
                    }
                }

                Text {
                    text: "version " + version;
                    font-size: 20px;
                    horizontal-alignment: right;
                    vertical-alignment: center;
                    vertical-stretch: 0;
                }
            }

            AboutSlint {
                horizontal-stretch: 0;
                vertical-stretch: 0;
            }

            Rectangle {
                vertical-stretch: 1;
            }

            HorizontalBox {
                alignment: end;
                vertical-stretch: 0;

                StandardButton {
                    kind: ok;
                    clicked => root.close();
                }
            }
        }
    }
}
