import {
    AboutSlint,
    Button,
    VerticalBox,
    HorizontalBox,
} from "std-widgets.slint";
import { Icons } from "../icons.slint";

export component AboutDialog inherits Window {
    title: "About BletchMAME";
    icon: Icons.bletchmame;
    in property <string> version;

    HorizontalBox {
        Image {
            width: 192px;
            height: 192px;
            source: Icons.bletchmame;
        }

        VerticalBox {
            Text {
                text: "BletchMAME " + version;
                font-size: 24px;
                horizontal-alignment: center;
            }

            AboutSlint {
                height: 100px;
            }
        }
    }
}
