import {
    Button,
    HorizontalBox,
    VerticalBox,
    TabWidget,
    ComboBox,
    GridBox,
    StandardButton,
    ListView,
    CheckBox,
    ScrollView,
    StandardTableView,
} from "std-widgets.slint";
import {
    DevicesAndImagesList,
    DevicesAndImagesState,
    DevicesAndImagesContextMenuInfo,
} from "../devimageslist.slint";
import { Icons } from "../icons.slint";
import { ToolTipArea } from "../tooltip.slint";
import { VideoConfigComponent, VideoSettings } from "../videoconfig.slint";

struct SoftwareMachine {
    machine-index: int,
    description: string,
    checked: bool}

struct Asset {
    icon: image,
    overlay: image,
    name: string,
    size: string,
    tooltip-text: string,
    browse-command: string,
}

export component ConfigureDialog inherits Window {
    title: dialog-title;
    icon: Icons.bletchmame;
    preferred-width: 600px;
    preferred-height: 500px;

    // properties
    in property <string> dialog-title;
    in property <DevicesAndImagesState> dev-images-state;
    in property <string> dev-images-error;
    in property <[string]> ram-sizes-model;
    in-out property <int> ram-sizes-index;
    in property <[string]> bios-selection-model;
    in-out property <int> bios-selection-index;
    in property <[Asset]> audit-assets;
    in property <string> audit-context-menu-browse-command;
    in property <[SoftwareMachine]> software-machines;
    in property <bool> software-machines-bulk-all-enabled;
    in property <bool> software-machines-bulk-none-enabled;
    in-out property <VideoSettings> video-settings: { prescale: 20 };
    in property <VideoSettings> video-default-settings: { prescale: 1 };
    in-out property <bool> video-use-default-settings: true;

    // callbacks
    callback ok-clicked();
    callback cancel-clicked();
    callback reset-clicked();
    callback entry-option-changed(int, string);
    callback entry-button-clicked(int, Point);
    callback menu-item-action(string);
    callback run-audit-clicked();
    callback software-machines-toggle-checked(int);
    callback software-machines-bulk-all-clicked();
    callback software-machines-bulk-none-clicked();

    // functions
    public function show-context-menu(info: DevicesAndImagesContextMenuInfo, point: Point) {
        dev-images-list.show-context-menu(info, point);
    }

    // control hierarchy
    VerticalBox {
        GridLayout {
            TabWidget {
                row: 0;
                col: 0;
                visible: root.software-machines.length == 0;
                Tab {
                    title: "Devices";
                    GridBox {
                        dev-images-list := DevicesAndImagesList {
                            visible: root.dev-images-error == "";
                            state: root.dev-images-state;
                            images-button-enabled: true;
                            entry-option-changed(index, option-name) => {
                                root.entry-option-changed(index, option-name);
                            }
                            entry-button-clicked(index, point) => {
                                root.entry-button-clicked(index, point);
                            }
                            menu-item-action(action) => {
                                root.menu-item-action(action);
                            }
                        }

                        Text {
                            visible: root.dev-images-error != "";
                            text: root.dev-images-error;
                        }
                    }
                }

                Tab {
                    title: "General";
                    VerticalBox {
                        alignment: start;
                        GridLayout {
                            Text {
                                row: 0;
                                col: 0;
                                vertical-alignment: center;
                                text: "RAM Size:";
                            }

                            ComboBox {
                                row: 0;
                                col: 1;
                                model: root.ram-sizes-model;
                                enabled: root.ram-sizes-model.length >= 2;
                                current-index <=> ram-sizes-index;
                            }

                            Text {
                                row: 1;
                                col: 0;
                                vertical-alignment: center;
                                text: "BIOS Selection:";
                            }

                            ComboBox {
                                row: 1;
                                col: 1;
                                model: root.bios-selection-model;
                                enabled: root.bios-selection-model.length >= 2;
                                current-index <=> bios-selection-index;
                            }
                        }
                    }
                }

                Tab {
                    title: "Audit";
                    VerticalBox {
                        ListView {
                            for asset in root.audit-assets: TouchArea {
                                ContextMenuArea {
                                    Menu {
                                        MenuItem {
                                            title: "Browse...";
                                            enabled: asset.browse-command != "";
                                            activated => {
                                                root.menu-item-action(asset.browse-command);
                                            }
                                        }
                                    }

                                    HorizontalBox {
                                        Rectangle {
                                            width: 24px;
                                            height: 24px;
                                            Image {
                                                width: 24px;
                                                height: 24px;
                                                source: asset.icon;
                                            }

                                            Image {
                                                width: 24px;
                                                height: 24px;
                                                source: asset.overlay;
                                            }
                                        }

                                        Text {
                                            text: asset.name;
                                            horizontal-stretch: 1;
                                            vertical-alignment: center;
                                        }

                                        Text {
                                            text: asset.size;
                                            vertical-alignment: center;
                                        }
                                    }
                                }

                                changed has-hover => {
                                    tooltip.show-tooltip(self.has-hover, self.absolute-position.x + self.mouse-x, self.absolute-position.y + self.mouse-y, asset.tooltip-text);
                                }
                            }
                        }

                        Button {
                            text: "Run Audit";
                            clicked => {
                                root.run-audit-clicked();
                            }
                        }
                    }
                }

                Tab {
                    title: "Video";
                    VerticalBox {
                        CheckBox {
                            checked <=> root.video-use-default-settings;
                            text: "Use global video settings";
                        }

                        VideoConfigComponent {
                            vertical-stretch: 1;
                            enabled: !root.video-use-default-settings;
                            changed settings => {
                                if (!root.video-use-default-settings) {
                                    root.video-settings = self.settings;
                                }
                            }
                            changed enabled => {
                                self.settings = self.enabled ? root.video-settings : root.video-default-settings;
                            }
                        }
                    }
                }
            }

            TabWidget {
                row: 0;
                col: 0;
                visible: root.software-machines.length > 0;
                Tab {
                    title: "Preferred Machines";
                    ListView {
                        preferred-height: 100%;
                        vertical-stretch: 1;
                        for data[row] in root.software-machines: HorizontalBox {
                            CheckBox {
                                width: 24px;
                                checked: data.checked;
                                toggled => {
                                    root.software-machines-toggle-checked(row);
                                }
                            }

                            Text {
                                text: data.description;
                            }
                        }
                    }
                }
            }
        }

        HorizontalBox {
            alignment: end;
            if root.software-machines.length == 0: StandardButton {
                max-height: 30px;
                kind: reset;
                clicked => {
                    root.reset-clicked();
                }
            }
            if root.software-machines.length > 0: Button {
                text: "Select All";
                enabled: root.software-machines-bulk-all-enabled;
                clicked => {
                    root.software-machines-bulk-all-clicked();
                }
            }
            if root.software-machines.length > 0: Button {
                text: "Select None";
                enabled: root.software-machines-bulk-none-enabled;
                clicked => {
                    root.software-machines-bulk-none-clicked();
                }
            }
            StandardButton {
                max-height: 30px;
                kind: cancel;
                clicked => {
                    root.cancel-clicked();
                }
            }

            StandardButton {
                max-height: 30px;
                kind: ok;
                enabled: root.dev-images-error == "";
                clicked => {
                    root.ok-clicked();
                }
            }
        }
    }

    tooltip := ToolTipArea { }
}
