import {
    VerticalBox,
    GridBox,
    HorizontalBox,
    StandardButton,
    ComboBox,
    ListView,
} from "std-widgets.slint";
import { Icons } from "../icons.slint";
import { HorizontalSplitter } from "../splitter.slint";

export struct ImportMameIniDialogEntry {
    path-type: string,
    path: string,
    current-disposition-index: int,
    dispositions: [string]
}

export component ImportMameIniDialog inherits Dialog {
    title: "Import MAME INI";
    icon: Icons.bletchmame;
    preferred-width: 600px;
    preferred-height: 500px;
    forward-focus: cancel-button;

    // properties
    in-out property <length> column-1-width: 150px;
    in-out property <length> column-2-width: 150px;
    in-out property <[ImportMameIniDialogEntry]> entries;
    in property <string> message-text;
    in property <bool> ok-enabled;

    // callbacks
    callback ok-clicked();
    callback cancel-clicked();

    // widgets
    VerticalBox {
        Text {
            text: @tr("The following settings from the specified MAME INI file can be imported to BletchMAME:");
        }

        ListView {
            for entry[idx] in entries: HorizontalLayout {
                height: 30px;
                width: parent.width;

                Text {
                    width: root.column-1-width;
                    text: entry.path-type;
                }

                HorizontalSplitter {
                    value <=> root.column-1-width;
                    min-value: 10px;
                }

                Text {
                    text: entry.path;
                }

                HorizontalSplitter {
                    value <=> root.column-2-width;
                    min-value: 10px;
                    multiple: -1.0;
                }

                ComboBox {
                    width: root.column-2-width;
                    model: entry.dispositions;
                    current-index: entry.current-disposition-index;
                    enabled: entry.dispositions.length > 1;
                    selected(_) => {
                        root.entries[idx].current-disposition-index = self.current-index;
                    }
                }
            }
        }

        Text {
            text: message-text;
        }

        HorizontalBox {
            alignment: end;
            StandardButton {
                kind: ok;
                horizontal-stretch: 0;
                enabled: ok-enabled;
                clicked => {
                    root.ok-clicked();
                }
            }

            cancel-button := StandardButton {
                kind: cancel;
                horizontal-stretch: 0;
                clicked => {
                    root.cancel-clicked();
                }
            }
        }
    }
}
