import { Button, VerticalBox, HorizontalBox, LineEdit, StandardButton } from "std-widgets.slint";
import { Icons } from "../icons.slint";

export component ConnectToSocketDialog inherits Window {
    title: "Connect To Socket";
    icon: Icons.bletchmame;
    height: 150px;
    width: 350px;
    callback accepted();
    callback cancelled();
    callback changed();
    in property <bool> can-accept;
    in-out property <string> host-text;
    in-out property <string> port-text;
    VerticalBox {
        Text {
            horizontal-alignment: left;
            text: "Enter Hostname of Host or IP Address and Port:";
        }

        HorizontalBox {
            LineEdit {
                text <=> root.host-text;
                accepted => {
                    root.accepted();
                }
                edited => {
                    root.changed();
                }
            }

            LineEdit {
                width: 100px;
                text <=> root.port-text;
                input-type: number;
                accepted => {
                    root.accepted();
                }
                edited => {
                    root.changed();
                }
            }
        }

        HorizontalBox {
            alignment: end;
            StandardButton {
                kind: cancel;
                clicked => {
                    root.cancelled();
                }
            }

            StandardButton {
                kind: ok;
                enabled: root.can-accept;
                clicked => {
                    root.accepted();
                }
            }
        }
    }
}
