import {
    Button,
    GridBox,
    HorizontalBox,
    StandardButton,
    Slider,
    TextEdit,
    VerticalBox,
} from "std-widgets.slint";
import { Icons } from "../icons.slint";
import { VideoConfigComponent, VideoSettings } from "../videoconfig.slint";

export component VideoDialog inherits Window {
    // callbacks
    callback ok-clicked();
    callback cancel-clicked();

    // properties
    in-out property <VideoSettings> settings: default-settings;
    in property <VideoSettings> original-settings: default-settings;
    in property <VideoSettings> default-settings: { prescale: 1 };
    property <length> label-width: 140px;

    // controls
    title: "Video";
    icon: Icons.bletchmame;
    VerticalBox {
        video-config-component := VideoConfigComponent {
            vertical-stretch: 1;
            settings <=> root.settings;
        }

        HorizontalBox {
            alignment: end;
            vertical-stretch: 0;
            Button {
                enabled: root.settings != root.default-settings;
                text: "Reset To Default";
                clicked => {
                    root.settings = root.default-settings;
                }
            }

            StandardButton {
                kind: ok;
                clicked => {
                    root.ok-clicked();
                }
                enabled: root.settings != root.original-settings;
            }

            StandardButton {
                kind: cancel;
                clicked => {
                    root.cancel-clicked();
                }
            }
        }
    }
}
