import {
    StandardListView,
    HorizontalBox,
    VerticalBox,
    StandardButton,
    CheckBox,
} from "std-widgets.slint";
import { Icons } from "../../icons.slint";

export component InputSelectMultipleDialog inherits Window {
    // properties
    in-out property <[string]> entries;
    
    // callbacks
    callback ok-clicked();
    callback cancel-clicked();
    callback checkbox-toggled(int, bool);

    // control hierarchy
    title: "Multiple";
    icon: Icons.bletchmame;
    VerticalBox {
        for text[i] in entries: CheckBox {
            text: text;
            toggled() => {
                checkbox-toggled(i, self.checked);
            }
        }
        HorizontalBox {
            alignment: end;
            StandardButton {
                kind: ok;
                clicked => {
                    root.ok-clicked();
                }
            }

            StandardButton {
                kind: cancel;
                clicked => {
                    root.cancel-clicked();
                }
            }
        }
    }
}
