import {
    VerticalBox,
    GridBox,
    HorizontalBox,
    Button,
    StandardButton,
} from "std-widgets.slint";
import { InputDialogEntry } from "input.slint";
import { SimpleMenuEntry } from "../../common.slint";
import { Icons } from "../../icons.slint";

component InputXyPart {
    // properties
    in property <InputDialogEntry> entry;

    // callbacks
    callback menu-item-action(string);
    callback context-button-clicked(Point);

    // widgets
    VerticalBox {
        visible: !(entry.name.is-empty && entry.text.is-empty && entry.primary-action.is-empty);
        Text {
            text: entry.text;
        }

        HorizontalBox {
            Button {
                text: entry.name;
                enabled: !entry.primary-action.is-empty;
                clicked => {
                    root.menu-item-action(entry.primary-action);
                }
            }

            Button {
                width: 40px;
                text: "▼";
                clicked => {
                    root.context-button-clicked({ x: self.absolute-position.x, y: self.absolute-position.y + self.height });
                }
            }
        }
    }
}

export component InputXyDialog inherits Window {
    // properties
    in property <string> dialog-title;
    in property <InputDialogEntry> left-entry;
    in property <InputDialogEntry> right-entry;
    in property <InputDialogEntry> up-entry;
    in property <InputDialogEntry> down-entry;
    in property <string> clear-action;
    in property <string> restore-defaults-action;

    // callbacks
    callback ok-clicked();
    callback menu-item-action(string);
    callback left-context-button-clicked(Point);
    callback right-context-button-clicked(Point);
    callback up-context-button-clicked(Point);
    callback down-context-button-clicked(Point);

    // context menu
    in-out property <[SimpleMenuEntry]> context-menu-entries-1;
    in-out property <[SimpleMenuEntry]> context-menu-entries-2;
    public function show-context-menu(entries-1: [SimpleMenuEntry], entries-2: [SimpleMenuEntry], point: Point) {
        self.context-menu-entries-1 = entries-1;
        self.context-menu-entries-2 = entries-2;
        context-menu.show(point);
    }

    // context menu control
    context-menu := ContextMenuArea {
        Menu {
            for entry in context-menu-entries-1: MenuItem {
                title: entry.title;
                enabled: entry.action != "";
                activated => {
                    root.menu-item-action(entry.action);
                }
            }
            if context-menu-entries-1.length > 0: MenuSeparator { }
            for entry in context-menu-entries-2: MenuItem {
                title: entry.title;
                enabled: entry.action != "";
                activated => {
                    root.menu-item-action(entry.action);
                }
            }
        }
    }

    // control hierarchy
    title: dialog-title;
    icon: Icons.bletchmame;
    VerticalBox {
        GridBox {
            InputXyPart {
                col: 0;
                row: 1;
                entry: root.left-entry;
                menu-item-action(action) => {
                    root.menu-item-action(action);
                }
                context-button-clicked(point) => {
                    root.left-context-button-clicked(point);
                }
            }

            InputXyPart {
                col: 2;
                row: 1;
                entry: root.right-entry;
                menu-item-action(action) => {
                    root.menu-item-action(action);
                }
                context-button-clicked(point) => {
                    root.right-context-button-clicked(point);
                }
            }

            InputXyPart {
                col: 1;
                row: 0;
                entry: root.up-entry;
                menu-item-action(action) => {
                    root.menu-item-action(action);
                }
                context-button-clicked(point) => {
                    root.up-context-button-clicked(point);
                }
            }

            InputXyPart {
                col: 1;
                row: 2;
                entry: root.down-entry;
                menu-item-action(action) => {
                    root.menu-item-action(action);
                }
                context-button-clicked(point) => {
                    root.down-context-button-clicked(point);
                }
            }
        }

        HorizontalBox {
            Button {
                text: "Clear";
                enabled: !clear-action.is-empty;
                clicked => {
                    root.menu-item-action(clear-action);
                }
            }

            Button {
                text: "Restore Defaults";
                enabled: !restore-defaults-action.is-empty;
                clicked => {
                    root.menu-item-action(restore-defaults-action);
                }
            }

            StandardButton {
                kind: ok;
                clicked => {
                    root.ok-clicked();
                }
            }
        }
    }
}
