import { AboutSlint, Button, VerticalBox, HorizontalBox } from "std-widgets.slint";

export component AboutDialog inherits Window {
    title: "About BletchMAME";
    icon: @image-url("bletchmame.png");
    HorizontalBox {
        Image {
            width: 192px;
            height: 192px;
            source: @image-url("bletchmame.png");
        }

        VerticalBox {
            Text {
                text: "BletchMAME";
                font-size: 24px;
                horizontal-alignment: center;
            }

            AboutSlint {
                height: 100px;
            }
        }
    }
}
