import { HorizontalBox, VerticalBox, ListView, CheckBox, Button } from "std-widgets.slint";

struct BuiltinCollectionDisplay {
    checked: bool,
    original_checked: bool,
    text: string,
    comments: string}

export component BuiltinCollectionsDialog inherits Window {
    in-out property <[BuiltinCollectionDisplay]> model;
    in property <bool> ok_enabled;
    out property <bool> accepted;
    callback done();
    callback update_ok_enabled();
    title: @tr("BletchMAME");
    width: 300px;
    height: 500px;
    VerticalBox {
        ListView {
            for ent in model: HorizontalBox {
                CheckBox {
                    text: ent.text;
                    checked: ent.checked;
                    toggled => {
                        ent.checked = self.checked;
                        root.update_ok_enabled();
                    }
                }

                Text {
                    text: ent.comments;
                }
            }
        }

        HorizontalBox {
            Button {
                text: "Cancel";
                clicked => {
                    root.done();
                }
            }

            Button {
                text: "Ok";
                enabled: root.ok_enabled;
                clicked => {
                    root.accepted = true;
                    root.done();
                }
            }
        }
    }
}
