import { Button, HorizontalBox, VerticalBox, TabWidget, ComboBox, GridBox  } from "std-widgets.slint";
import { DevicesAndImagesList, DevicesAndImagesState } from "devimageslist.slint";

export component ConfigureDialog inherits Window {
    title: "Configure";
    icon: @image-url("bletchmame.png");
    preferred-width: 600px;
    preferred-height: 500px;

    // properties
    in property <DevicesAndImagesState> dev-images-state;
    in property <string> dev-images-error;
    in property <[string]> ram-sizes-model;
    in-out property <int> ram-sizes-index;

    // callbacks
    callback ok-clicked();
    callback entry-option-changed(int, string);
    callback entry-button-clicked(int, Point);
    callback menu-entry-activated(MenuEntry);

    // functions
    public function show-context-menu(entries: [MenuEntry], point: Point) {
        dev-images-list.show-context-menu(entries, point);
    }

    // control hierarchy
    VerticalBox {
        TabWidget {
            Tab {
                title: "Devices";
                GridBox {
                    preferred-width: 100%;
                    preferred-height: 100%;
                    dev-images-list := DevicesAndImagesList {
                        visible: root.dev-images-error == "";
                        state: root.dev-images-state;
                        images-button-enabled: true;
                        entry-option-changed(index, option-name) => {
                            root.entry-option-changed(index, option-name);
                        }
                        entry-button-clicked(index, point) => {
                            root.entry-button-clicked(index, point);
                        }
                        menu-entry-activated(entry) => {
                            root.menu-entry-activated(entry);
                        }
                    }

                    Text {
                        visible: root.dev-images-error != "";
                        text: root.dev-images-error;
                    }
                }
            }

            Tab {
                title: "RAM Sizes";
                VerticalBox {
                    alignment: start;
                    GridLayout {
                        Text {
                            row: 0;
                            col: 0;
                            vertical-alignment: center;
                            text: "RAM Size:";
                        }

                        ComboBox {
                            row: 0;
                            col: 1;
                            model: root.ram-sizes-model;
                            enabled: root.ram-sizes-model.length >= 2;
                            current-index <=> ram-sizes-index;
                        }
                    }
                }
            }
        }

        HorizontalBox {
            alignment: end;
            Button {
                max-height: 30px;
                text: "Ok";
                enabled: root.dev-images-error == "";
                clicked => {
                    root.ok-clicked();
                }
            }
        }
    }
}
