import {
    Button,
    VerticalBox,
    HorizontalBox,
    ComboBox,
    ListView,
    LineEdit,
} from "std-widgets.slint";

import { SimpleMenuEntry } from "common.slint";
import { HorizontalSplitter } from "splitter.slint";

export struct DeviceAndImageEntry {
    indent: int,
    display-tag: string,
    option-names: [string],
    option-descriptions: [string],
    current-option-index: int,
    filename: string}

export struct DevicesAndImagesState {
    entries: [DeviceAndImageEntry],
    none-string: string}

export struct DevicesAndImagesContextMenuInfo {
    load-image-action: string,
    connect-to-serial-port-actions: [SimpleMenuEntry],
    connect-to-socket-action: string,
    unload-action: string}

export component DevicesAndImagesList {
    // properties
    in property <DevicesAndImagesState> state;
    in property <bool> images-button-enabled;
    in-out property <length> splitter-x: 240px;
    in-out property <length> splitter-width: 5px;
    property <length> button-width: 30px;

    // callbacks
    callback entry-option-changed(int, string);
    callback entry-button-clicked(int, Point);
    callback menu-item-action(string);

    // context menu
    in-out property <DevicesAndImagesContextMenuInfo> context-menu-info;
    public function show-context-menu(info: DevicesAndImagesContextMenuInfo, point: Point) {
        self.context-menu-info = info;
        context-menu.show(point);
    }

    // context menu control
    context-menu := ContextMenuArea {
        Menu {
            MenuItem {
                title: @tr("DevicesAndImages" => "Create Image...");
                enabled: false;
            }

            MenuItem {
                title: @tr("DevicesAndImages" => "Load Image...");
                enabled: root.context-menu-info.load-image-action != "";
                activated => {
                    menu-item-action(root.context-menu-info.load-image-action);
                }
            }

            MenuItem {
                title: @tr("DevicesAndImages" => "Load Software List Part...");
                enabled: false;
            }

            Menu {
                title: @tr("DevicesAndImages" => "Connect To Serial Port");
                for entry in root.context-menu-info.connect-to-serial-port-actions: MenuItem {
                    title: entry.title;
                    enabled: entry.action != "";
                    activated => {
                        menu-item-action(entry.action);
                    }
                }
                if root.context-menu-info.connect-to-serial-port-actions.length == 0: MenuItem {
                    title: @tr("DevicesAndImages" => "(no serial ports found)");
                    enabled: false;
                }
            }

            MenuItem {
                title: @tr("DevicesAndImages" => "Connect To Socket...");
                enabled: root.context-menu-info.connect-to-socket-action != "";
                activated => {
                    menu-item-action(root.context-menu-info.connect-to-socket-action);
                }
            }

            MenuItem {
                title: @tr("DevicesAndImages" => "Unload");
                enabled: root.context-menu-info.unload-action != "";
                activated => {
                    menu-item-action(root.context-menu-info.unload-action);
                }
            }
        }
    }

    // controls
    ListView {
        for data[index] in root.state.entries: Rectangle {
            height: 30px;
            width: parent.width;
            Text {
                x: data.indent * 20px;
                text: data.display_tag;
            }

            ComboBox {
                x: root.splitter-x + root.splitter-width;
                width: root.width - (root.splitter-x + root.splitter-width);
                visible: data.current-option-index >= 0;
                model: data.option-descriptions;
                current-index: data.current-option-index;
                selected(value) => {
                    root.entry-option-changed(index, data.option-names[self.current-index]);
                }
            }

            LineEdit {
                x: root.splitter-x + root.splitter-width;
                width: root.width - (root.splitter-x + root.splitter-width) - root.button-width;
                visible: data.current-option-index < 0;
                placeholder-text: root.state.none-string;
                text: data.filename;
                read-only: true;
            }

            Button {
                x: root.width - root.button-width;
                width: root.button-width;
                visible: data.current-option-index < 0;
                enabled: root.images-button-enabled;
                text: "...";
                clicked => {
                    root.entry-button-clicked(index, { x: self.absolute-position.x, y: self.absolute-position.y + self.height });
                }
            }
        }
    }

    HorizontalSplitter {
        x <=> root.splitter-x;
        width: root.splitter-width;
        height: 100%;
    }
}
