import { Icons as ViviIcons } from "@vivi/magic.slint";

export global Icons {
    out property <image> bletchmame: @image_url("bletchmame.png");
    out property <image> arrow-back: @image_url("icons/arrow-back.svg");
    out property <image> arrow-forward: @image_url("icons/arrow-forward.svg");
    out property <image> book: @image_url("icons/book.svg");
    out property <image> folder: ViviIcons.folder;
    out property <image> search: ViviIcons.search;
}
