export global Icons {
    out property <image> bletchmame: @image_url("icons/bletchmame.png");
    out property <image> bletchmame-blank: @image_url("icons/bletchmame-blank.png");
    out property <image> arrow-back: @image_url("icons/arrow-back.svg");
    out property <image> arrow-forward: @image_url("icons/arrow-forward.svg");
    out property <image> book: @image_url("icons/book.svg");
    out property <image> folder: @image_url("icons/folder.svg");
    out property <image> search: @image_url("icons/search.svg");
    out property <image> search-text: @image_url("icons/search-text.svg");
}
