import { VerticalBox, GridBox, HorizontalBox, StandardButton, ComboBox, ListView } from "std-widgets.slint";
import { Icons } from "icons.slint";

export struct ImportMameIniDialogEntry {
    path-type: string,
    path: string,
    current-disposition-index: int,
    dispositions: [string]
}

export component ImportMameIniDialog inherits Window {
    title: "Import MAME INI";
    icon: Icons.bletchmame;
    preferred-width: 600px;
    preferred-height: 500px;

    // properties
    in property <length> splitter-1: 120px;
    in property <length> splitter-2: root.width - 150px;
    in-out property <[ImportMameIniDialogEntry]> entries;
    in property <string> message-text;
    in property <bool> ok-enabled;

    // callbacks
    callback ok-clicked();
    callback cancel-clicked();

    // widgets
    VerticalBox {
        Text {
            text: @tr("The following settings from the specified MAME INI file can be imported to BletchMAME:");
        }

        ListView {
            for entry[idx] in entries: Rectangle {
                height: 30px;
                width: parent.width;
                Text {
                    x: 0px;
                    text: entry.path-type;
                }

                Text {
                    x: splitter-1;
                    text: entry.path;
                }

                ComboBox {
                    x: splitter-2;
                    model: entry.dispositions;
                    current-index: entry.current-disposition-index;
                    enabled: entry.dispositions.length > 1;
                    selected(_) => {
                        root.entries[idx].current-disposition-index = self.current-index;
                    }
                }
            }
        }

        Text {
            text: message-text;
        }

        HorizontalBox {
            alignment: end;
            StandardButton {
                kind: ok;
                horizontal-stretch: 0;
                enabled: ok-enabled;
                clicked => {
                    root.ok-clicked();
                }
            }

            StandardButton {
                kind: cancel;
                horizontal-stretch: 0;
                clicked => {
                    root.cancel-clicked();
                }
            }
        }
    }
}
