import { GridBox, VerticalBox, HorizontalBox, Button, StandardButton, ScrollView } from "std-widgets.slint";

export struct InputDialogEntry {
    name: string,
    text: string}

export component InputDialog inherits Window {
    title: dialog-title;
    icon: @image-url("bletchmame.png");
    preferred-width: 600px;
    preferred-height: 500px;

    // properties
    in property <string> dialog-title;
    in property <[InputDialogEntry]> entries;

    // callbacks
    callback ok-clicked();

    // control hierarchy
    VerticalBox {
        ScrollView {
            viewport-height: root.entries.length * 30px;
            VerticalBox {
                padding: 3px;
                for entry in root.entries: HorizontalLayout {
                    vertical-stretch: 0;
                    Button {
                        width: 300px;
                        text: entry.name;
                        enabled: false;
                    }

                    Button {
                        width: 40px;
                        text: "▼";
                        enabled: false;
                    }

                    VerticalLayout {
                        alignment: center;
                        Text {
                            width: 100%;
                            text: entry.text;
                        }
                    }
                }
            }
        }

        HorizontalBox {
            alignment: end;
            Button {
                text: @tr("Restore Defaults");
                horizontal-stretch: 0;
                enabled: false;
            }

            StandardButton {
                kind: ok;
                horizontal-stretch: 0;
                clicked => {
                    root.ok-clicked();
                }
            }
        }
    }
}
