import { GridBox, VerticalBox, HorizontalBox, Button, StandardButton, ScrollView } from "std-widgets.slint";

export struct InputDialogEntry {
    name: string,
    text: string}

export struct InputContextMenuEntry {
    title: string,
    command: string}
    
export component InputDialog inherits Window {
    title: dialog-title;
    icon: @image-url("bletchmame.png");
    preferred-width: 600px;
    preferred-height: 500px;

    // properties
    in property <string> dialog-title;
    in property <[InputDialogEntry]> entries;

    // callbacks
    callback ok-clicked();
    callback context-button-clicked(int, Point);
    callback menu-item-command(string);

    // context menu
    in-out property <[InputContextMenuEntry]> context-menu-entries-1;
    in-out property <[InputContextMenuEntry]> context-menu-entries-2;
    public function show-context-menu(entries-1: [InputContextMenuEntry], entries-2: [InputContextMenuEntry], point: Point) {
        self.context-menu-entries-1 = entries-1;
        self.context-menu-entries-2 = entries-2;
        context-menu.show(point);
    }

    // context menu control
    context-menu := ContextMenuArea {
        Menu {
            for entry in context-menu-entries-1: MenuItem {
                title: entry.title;
                enabled: entry.command != "";
                activated => {
                    root.menu-item-command(entry.command);
                }
            }
            if context-menu-entries-1.length > 0: MenuSeparator { }
            for entry in context-menu-entries-2: MenuItem {
                title: entry.title;
                enabled: entry.command != "";
                activated => {
                    root.menu-item-command(entry.command);
                }
            }
        }
    }

    // control hierarchy
    VerticalBox {
        ScrollView {
            viewport-height: root.entries.length * 30px;
            VerticalBox {
                padding: 3px;
                for entry[index] in root.entries: HorizontalLayout {
                    vertical-stretch: 0;
                    Button {
                        width: 300px;
                        text: entry.name;
                        enabled: false;
                    }

                    Button {
                        width: 40px;
                        text: "▼";
                        enabled: true;
                        clicked => {
                            root.context-button-clicked(index, { x: self.absolute-position.x, y: self.absolute-position.y + self.height });
                        }
                    }

                    VerticalLayout {
                        alignment: center;
                        Text {
                            width: 100%;
                            text: entry.text;
                        }
                    }
                }
            }
        }

        HorizontalBox {
            alignment: end;
            Button {
                text: @tr("Restore Defaults");
                horizontal-stretch: 0;
                enabled: false;
            }

            StandardButton {
                kind: ok;
                horizontal-stretch: 0;
                clicked => {
                    root.ok-clicked();
                }
            }
        }
    }
}
