import { HorizontalBox, VerticalBox, Button, StandardListView, StandardTableView, LineEdit, ListView } from "std-widgets.slint";
import { MagicListView, MagicListViewItem, Icons, FilledButton } from "@vivi/magic.slint";
import { LoadingDialog } from "loading.slint";

export { LoadingDialog, Icons }

export component AppWindow inherits Window {
    min-width: 100px;
    min-height: 100px;
    max-width: 10000px;
    max-height: 10000px;
    title: @tr("BletchMAME 3.0 prototype");
    callback find_mame_clicked();
    in property <bool> is_running;
    in property <bool> has_info_db;
    in property <bool> history-can-go-back;
    in property <bool> history-can-go-forward;
    in-out property <int> items-view-selected-index <=> items-table-view.current-row;
    in-out property <string> items-search-text;
    in-out property <[TableColumn]> items-columns <=> items-table-view.columns;
    callback collections-view-selected(int);
    callback items-search-text-changed(string);
    callback items-sort-ascending(int);
    callback items-sort-descending(int);
    callback items-row-pointer-event(int, PointerEvent, Point);
    callback history-advance-clicked(int);
    in property <[MagicListViewItem]> collections-model;
    in property <[[StandardListViewItem]]> items-model;
    public function collections-view-select(index: int) {
        collections-list-view.current_index = index;
    }
    public function items-view-select(index: int) {
        items-table-view.set-current-row(index);
    }
    VerticalBox {
        alignment: center;
        Text {
            text: @tr("BletchMAME needs a working MAME to function");
            font-size: 24px;
            wrap: word-wrap;
        }

        Button {
            text: @tr("Find MAME...");
            clicked => {
                root.find_mame_clicked();
            }
        }

        width: 300px;
        visible: !has_info_db;
    }

    HorizontalBox {
        visible: has_info_db && !is_running;
        collections-list-view := MagicListView {
            width: 250px;
            preferred-height: 100%;
            model: collections-model;
            selected(index) => {
                collections-view-selected(index)
            }
        }

        VerticalBox {
            HorizontalBox {
                FilledButton {
                    icon: Icons.arrow_back;
                    enabled: history-can-go-back;
                    clicked => {
                        history-advance-clicked(-1)
                    }
                }

                FilledButton {
                    icon: Icons.book;
                    enabled: false;
                }

                FilledButton {
                    icon: Icons.arrow_forward;
                    enabled: history-can-go-forward;
                    clicked => {
                        history-advance-clicked(+1)
                    }
                }

                LineEdit {
                    text: items-search-text;
                    edited(text) => {
                        items-search-text-changed(text)
                    }
                }
            }

            items-table-view := StandardTableView {
                columns: [{ }, { }, { }, { }, { }];
                rows: items_model;
                preferred-width: 100%;
                preferred-height: 100%;
                sort-ascending(index) => {
                    items-sort-ascending(index)
                }
                sort-descending(index) => {
                    items-sort-descending(index)
                }
                row-pointer-event(row, event, point) => {
                    items-row-pointer-event(row, event, point)
                }
            }
        }
    }
}
