import { Icons } from "@vivi/magic.slint";
import { AboutDialog } from "about.slint";
import { LoadingDialog } from "loading.slint";
import { PathsDialog } from "paths.slint";
import { MessageBoxDialog } from "messagebox.slint";
import { NameCollectionDialog } from "namecollection.slint";
import { ConnectToSocketDialog } from "socket.slint";
import { DevicesAndImagesDialog } from "devimages.slint";
import { DeviceAndImageEntry } from "devimageslist.slint";
import { AppWindow } from "appwindow.slint";
import { ConfigureDialog } from "configure.slint";

export { AboutDialog, AppWindow, ConfigureDialog, ConnectToSocketDialog, LoadingDialog, MessageBoxDialog, NameCollectionDialog, PathsDialog, DevicesAndImagesDialog, DeviceAndImageEntry, Icons }
