import { AboutSlint, Button, VerticalBox, HorizontalBox, LineEdit } from "std-widgets.slint";

export component NameCollectionDialog inherits Window {
    title: title-text;
    width: 400px;
    height: 100px;
    callback ok-clicked();
    callback cancel-clicked();
    callback text-edited(string);
    out property <string> text;
    in property <string> title-text;
    in-out property <bool> ok-enabled;
    public function set-text(text: string) {
        line-edit.text = text;
        line-edit.select-all();
        line-edit.focus();
    }
    VerticalBox {
        line-edit := LineEdit {
            text <=> root.text;
            height: 30px;
            edited(new-text) => {
                text-edited(new-text);
            }
            accepted(new-text) => {
                if ok-enabled {
                    root.ok-clicked();
                }
            }
        }

        HorizontalBox {
            alignment: end;
            Button {
                text: "Cancel";
                clicked => {
                    root.cancel-clicked();
                }
                width: 80px;
                height: 30px;
            }

            Button {
                text: "Ok";
                clicked => {
                    root.ok-clicked();
                }
                width: 80px;
                height: 30px;
                enabled <=> ok-enabled;
            }
        }
    }
}
