import {
    HorizontalBox,
    VerticalBox,
    Button,
    ScrollView,
    Spinner,
    TextEdit,
} from "std-widgets.slint";
import { AuditAsset, AuditAssetView } from "audit.slint";

struct ReportIssue { text: string, button-text: string }

export struct Report {
    message: string,
    submessage: string,
    mame-stderr-output: string,
    mame-exit-code: string,
    spinning: bool,
    spinning-progress: float,
    button1-text: string,
    button1-action: string,
    button2-text: string,
    button2-action: string,
    issues: [ReportIssue],
    audit-results: [AuditAsset],
}

export component ReportView {
    in property <Report> report;
    callback issue-button-clicked(int);
    callback menu-item-action(string);

    property <string> monospace-font-family: "Consolas";

    height: 100%;

    HorizontalBox {
        alignment: center;
        visible: report.message != "";

        if report.spinning: VerticalBox {
            alignment: center;
            Spinner {
                width: 150px;
                height: 150px;
                indeterminate: report.spinning-progress < 0.0;
                progress: report.spinning-progress;
            }
        }

        VerticalBox {
            alignment: center;
            height: 100%;
            width: 100%;

            // report message
            Text {
                text: report.message;
                horizontal-alignment: center;
                font-size: 24px;
                wrap: word-wrap;
            }

            // report submessage
            if report.submessage != "": Text {
                text: report.submessage;
                horizontal-alignment: center;
                font-size: 12px;
                wrap: word-wrap;
            }

            // report MAME stderr output
            if report.mame-stderr-output != "": TextEdit {
                width: 600px;
                height: 300px;
                text: report.mame-stderr-output;
                font-size: 10px;
                font-family: monospace-font-family;
                read-only: true;
            }

            // report MAME exit code
            if report.mame-exit-code != "": Text {
                text: "(exit code " + report.mame-exit-code + "}";
                horizontal-alignment: right;
                font-size: 12px;
            }

            if report.button1-text != "" || report.button2-text != "": HorizontalBox {
                alignment: center;
                // report button 1
                if report.button1-text != "": Button {
                    text: report.button1-text;
                    clicked => {
                        menu-item-action(report.button1-action);
                    }
                }

                // report button 2
                if report.button2-text != "": Button {
                    text: report.button2-text;
                    clicked => {
                        menu-item-action(report.button2-action);
                    }
                }
            }

            // report issues
            for issue[index] in report.issues: HorizontalBox {
                Text {
                    horizontal-alignment: left;
                    text: issue.text;
                }

                Button {
                    visible: issue.button-text != "";
                    text: issue.button-text;
                    clicked => {
                        issue-button-clicked(index);
                    }
                }
            }

            // report audit assets
            if report.audit-results.length > 0: ScrollView {
                height: 100%;
                width: 450px;
                vertical-scrollbar-policy: always-on;
                VerticalLayout {
                    for asset in report.audit-results: AuditAssetView {
                        asset: asset;
                        menu-item-action(action) => {
                            menu-item-action(action);
                        }
                    }
                }
            }
        }
    }
}
