
import { VerticalBox, HorizontalBox, Button } from "std-widgets.slint";
import { Icons } from "icons.slint";

export component SeqPollDialog inherits Window {
    title: dialog-title;
    icon: Icons.bletchmame;

    // properties
    in property <string> dialog-title;
    in property <string> dialog-caption;
    in property <[string]> mouse-input-titles;

    // callbacks
    callback mouse-input-selected(int);

    // mouse context menu control
    mouse-context-menu := ContextMenuArea {
        Menu {
            for titles[index] in mouse-input-titles: MenuItem {
                title: titles;
                enabled: true;
                activated => {
                    root.mouse-input-selected(index);
                }
            }
        }
    }

    // controls
    VerticalBox {
        Text {
            text: dialog-caption;
        }

        HorizontalBox {
            Text {
                text: "For mouse inputs, press the button to the right";
                vertical-alignment: center;
            }

            Button {
                text: "Mouse Inputs";
                enabled: mouse-input-titles.length > 0;
                clicked => {
                    mouse-context-menu.show({ x: self.absolute-position.x, y: self.absolute-position.y + self.height });
                }
            }
        }
    }
}
