on: [push, pull_request]

name: General

jobs:
  grcov:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: minimal
