########################################
# BletchMAME Github Action             #
########################################

on:
    push:
        branches:
        - master
    pull_request:
        branches:
        - master

name: General

jobs:
  test:
    name: Test Suite
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        qt: [true, false]
        exclude:
          - os: windows-latest
            qt: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y libxdo-dev libpango1.0-dev libgtk-3-dev
      - name: Install Qt
        if: ${{ matrix.qt == 'true' }}
        uses: jurplel/install-qt-action@v4          
      - name: Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}
      - name: Test Suite
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: ${{ matrix.qt == 'true' && '--all-features' || '' }}

  diagnostics:
    name: Diagnostics
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y libxdo-dev libpango1.0-dev libgtk-3-dev mame
      - name: Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}
      - name: Diagnostics
        run: |
          mame -listxml | cargo run --release -- --process-listxml

  clippy:
    name: Clippy
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        qt: [true, false]
        exclude:
          - os: windows-latest
            qt: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install Rust Components
        run: rustup component add clippy
      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y libxdo-dev libpango1.0-dev libgtk-3-dev
      - name: Install Qt
        if: ${{ matrix.qt == 'true' }}
        uses: jurplel/install-qt-action@v4          
      - name: Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-clippy-${{ hashFiles('**/Cargo.lock') }}
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: ${{ matrix.qt == 'true' && '--all-features --all-targets -- -D warnings' || '--all-targets -- -D warnings' }}

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
